name: Build Test Release
run-name: ${{ inputs.image_id }}

on:
  workflow_call:
    inputs:
      # e.g. ubuntu22-full-x64
      image_id:
        required: true
        type: string
      platform:
        required: false
        type: string
        default: "linux"
    outputs:
      ami_name:
        description: "The name of the built AMI"
        value: ${{ jobs.build.outputs.ami_name }}
      ami_id:
        description: "The ID of the built AMI"
        value: ${{ jobs.build.outputs.ami_id }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_id: ${{ inputs.image_id }}
    secrets: inherit

  test1:
    needs:
      - build
    uses: ./.github/workflows/test.yml
    with:
      ami_id: ${{ needs.build.outputs.ami_id }}
      index: 1
      platform: ${{ inputs.platform }}

  test2:
    needs:
      - build
      - test1
    uses: ./.github/workflows/test.yml
    with:
      ami_id: ${{ needs.build.outputs.ami_id }}
      index: 2
      platform: ${{ inputs.platform }}

  test-extras1:
    needs:
      - build
      - test2
    uses: ./.github/workflows/test.yml
    with:
      ami_id: ${{ needs.build.outputs.ami_id }}
      index: 3
      extras: "s3-cache"
      platform: ${{ inputs.platform }}

  test-extras2:
    needs:
      - build
      - test-extras1
    uses: ./.github/workflows/test.yml
    with:
      ami_id: ${{ needs.build.outputs.ami_id }}
      index: 4
      extras: "s3-cache"
      platform: ${{ inputs.platform }}

  test-gpu:
    if: contains(inputs.image_id, 'gpu-x64')
    needs:
      - build
      - test-extras2
    uses: ./.github/workflows/test.yml
    with:
      ami_id: ${{ needs.build.outputs.ami_id }}
      index: 5
      instance_family: "g4dn"
      platform: ${{ inputs.platform }}

  release:
    if: ${{ !failure() && !cancelled() }}
    needs:
      - build
      - test-gpu
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      image_id: ${{ inputs.image_id }}
      ami_name: ${{ needs.build.outputs.ami_name }}