name: Check x64

concurrency:
  group: check-x64

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */15 * 4"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PUSH: true
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: bundle exec bin/01-pull --arch x64 --force
        id: pull
      - run: bin/02-build ${{ steps.check.outputs.release_dir }}
        timeout-minutes: 300
        env:
          AMI_PREFIX: runs-on-dev
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ${{ steps.pull.outputs.release_dir }} from upstream"
      - if: always()
        # make sure we terminate instances even if workflow is canceled
        run: bin/cleanup-instances
