name: Test
run-name: Test ${{ inputs.ami_id }}

on:
  workflow_dispatch:
    inputs:
      ami_id:
        required: true
        type: string
  workflow_call:
    inputs:
      ami_id:
        required: true
        type: string

jobs:
  test:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        index: [1, 2, 3, 4, 5]
    name: Test${{ matrix.index }}
    runs-on:
      - runs-on
      - family=m7
      - cpu=2
      - ami=${{ inputs.ami_id }}
      - index=${{ matrix.index }}
    steps:
      - name: Logs
        run: sudo cat /var/log/cloud-init-output.log
      - name: Systemctl status
        run: sudo systemctl status
      - name: Disk
        run: |
          sudo df -ah
          sudo lsblk -l
      - name: env
        run: env | sort
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker
        run: docker run hello-world
      - name: envinfo
        run: npx envinfo
      - name: env
        run: env | sort
      - name: show HOME
        run: ls -al $HOME
      - name: rustup
        run: rustup --version
      - name: Do something
        run: |
          echo "Hello world from $HOSTNAME"
