name: Test
run-name: Test ${{ inputs.distribution }}-full-${{ inputs.architecture }}

on:
  workflow_dispatch:
    inputs:
      distribution:
        required: true
        type: string
      architecture:
        required: true
        type: string
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string
      architecture:
        required: true
        type: string

jobs:
  test:
    runs-on: runs-on,runner=2cpu-linux-${{ inputs.architecture }},image=${{ inputs.distribution }}-dev-${{ inputs.architecture }}
    steps:
      - name: Logs
        run: sudo cat /var/log/cloud-init-output.log
      - name: Systemctl status
        run: sudo systemctl status
      - name: Disk
        run: |
          sudo df -ah
          sudo lsblk -l
      - name: env
        run: env | sort
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker
        run: docker run hello-world
      - name: envinfo
        run: npx envinfo
      - name: env
        run: env | sort
      - name: show HOME
        run: ls -al $HOME
      - name: rustup
        run: rustup --version
      - name: Do something
        run: |
          echo "Hello world from $HOSTNAME"
