name: Test
run-name: Test ${{ inputs.ami_id }}

on:
  workflow_dispatch:
    inputs:
      ami_id:
        required: true
        type: string
      instance_family:
        required: true
        type: string
        default: "m7"
  workflow_call:
    inputs:
      ami_id:
        required: true
        type: string
      index:
        required: true
        type: number
      instance_family:
        required: true
        type: string
        default: "m7"

jobs:
  test:
    name: Test${{ inputs.index || '1' }}
    runs-on:
      - runs-on
      - family=${{ inputs.instance_family }}
      - cpu=2+4
      - ami=${{ inputs.ami_id }}
    steps:
      - name: Logs
        run: sudo cat /var/log/cloud-init-output.log
      - name: Systemctl status
        run: sudo systemctl status
      - name: Disk
        run: |
          sudo df -ah
          sudo lsblk -l
      - name: env
        run: env | sort
      - name: Ensure apt-get update is working
        run: sudo apt-get update
      - name: Ensure code can be checked out
        uses: actions/checkout@v4
      - name: Docker
        run: docker run hello-world
      - name: envinfo
        run: npx envinfo
      - name: env
        run: env | sort
      - name: show HOME
        run: ls -al $HOME
      - name: rustup
        run: rustup --version
      - name: Ensure NVIDIA drivers are ok
        if: contains(inputs.instance_family, 'g4dn')
        run: |
          nvidia-smi
          nvidia-smi -L
          nvidia-smi -q -d Memory
      - name: Do something
        run: |
          echo "Hello world from $HOSTNAME"
